root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main.exe ./cmd/server/main.go"
  bin = "./tmp/main.exe"
  delay = 1000
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", "frontend", "node_modules"]
  exclude_regex = ["_test\\.go"]

[log]
  main_only = true

[screen]
  clear_on_rebuild = true

[misc]
  clean_on_exit = true